# Simple Docker Build Pipeline
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

- script: |
    echo "✅ Docker build completed successfully!"
    echo "Build ID: $(Build.BuildId)"
  displayName: 'Build Complete'