version: '3.8'

services:
  backend:
    image: dhana1312/mess-feedback-backend:latest
    container_name: mess-feedback-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_SERVER=dailyfeedbacksystem.database.windows.net
      - DB_NAME=messdata
      - DB_USER=bhuvaneshwari@dailyfeedbacksystem
      - DB_PASSWORD=Friends54321
      - DB_PORT=1433
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped

  frontend:
    image: dhana1312/mess-feedback-frontend:latest
    container_name: mess-feedback-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    restart: unless-stopped
