version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: mess-feedback-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_SERVER=dailyfeedbacksystem.database.windows.net
      - DB_NAME=messdata
      - DB_USER=bhuvaneshwari@dailyfeedbacksystem
      - DB_PASSWORD=Friends54321
      - DB_PORT=1433
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mess-feedback-network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: mess-feedback-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mess-feedback-network
    restart: unless-stopped

networks:
  mess-feedback-network:
    driver: bridge