

version: '3.8'

services:
  backend:
    image: dhana1312/mess-feedback-backend:latest
    container_name: mess-feedback-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_SERVER=dailyfeedbacksystem.database.windows.net
      - DB_NAME=messdata
      - DB_USER=bhuvaneshwari
      - DB_PASSWORD=Friends54321
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - FRONTEND_URL=http://localhost:3000
    networks:
      - mess-feedback-network
    restart: unless-stopped

  frontend:
    image: dhana1312/mess-feedback-frontend:latest
    container_name: mess-feedback-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - mess-feedback-network
    restart: unless-stopped

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mess-feedback-database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    volumes:
      - database_data:/var/opt/mssql
    networks:
      - mess-feedback-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: mess-feedback-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - mess-feedback-network
    restart: unless-stopped

volumes:
  database_data:

networks:
  mess-feedback-network:
    driver: bridge