apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: mess-feedback-system
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/your-username/daily-mess-feedback-system-web-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mess-feedback-config
              key: DB_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mess-feedback-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mess-feedback-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mess-feedback-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mess-feedback-secrets
              key: JWT_SECRET
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mess-feedback-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: mess-feedback-config
              key: NODE_ENV
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
